const mechanics = [
  {
    id: "M001",
    name: "Hanumanth Gouda",
    nameKn: "ಹನುಮಂತ ಗೌಡ",
    lat: 15.3647,
    lng: 76.1547,
    faultHistory: {
      "Winding burnout": { jobs: 78, successRate: 98 },
      "Bearing seizure": { jobs: 45, successRate: 96 },
      "Capacitor failure": { jobs: 23, successRate: 100 },
      "Impeller damage": { jobs: 34, successRate: 94 }
    },
    hasVehicle: true,
    phone: "9876543210",
    experience: 12,
    shopName: "Sri Lakshmi Motor Rewinding",
    shopNameKn: "ಶ್ರೀ ಲಕ್ಷ್ಮಿ ಮೋಟರ್ ರಿವೈಂಡಿಂಗ್",
    location: "Koppal",
    locationKn: "ಕೊಪ್ಪಳ",
    serviceRadius: 30,
    serviceAreas: ["Koppal","Munirabad","Irkalgada","Bhagyanagar","Hosahalli","Kunikeri","Halageri","Hitnal"],
    skills: ["Submersible Pump", "Monoblock Pump"],
    skillsKn: ["ಸಬ್‌ಮರ್ಸಿಬಲ್ ಪಂಪ್", "ಮೋನೋಬ್ಲಾಕ್ ಪಂಪ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.9,
    completedJobs: 312
  },

  {
    id: "M002",
    name: "Basavaraj M",
    nameKn: "ಬಸವರಾಜ ಎಂ",
    lat: 15.4326,
    lng: 76.5315,
    faultHistory: {
      "Shaft breakage": { jobs: 15, successRate: 90 },
      "Starter panel fault": { jobs: 60, successRate: 99 },
      "Voltage fluctuation damage": { jobs: 40, successRate: 95 }
    },
    hasVehicle: false,
    phone: "9876543211",
    experience: 8,
    shopName: "Basava Pumps Service",
    shopNameKn: "ಬಸವ ಪಂಪ್ ಸರ್ವೀಸ್",
    location: "Gangavathi",
    locationKn: "ಗಂಗಾವತಿ",
    serviceRadius: 30,
    serviceAreas: ["Gangavathi","Kanakagiri","Karatagi","Marali","Herur","Sanganhal","Anjanadri","Anegundi"],
    skills: ["Openwell Pump", "Submersible Pump"],
    skillsKn: ["ಓಪನ್ ವೆಲ್ ಪಂಪ್", "ಸಬ್‌ಮರ್ಸಿಬಲ್ ಪಂಪ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.8,
    completedJobs: 198
  },

  {
    id: "M003",
    name: "Shivappa K",
    nameKn: "ಶಿವಪ್ಪ ಕೆ",
    lat: 15.7607,
    lng: 76.1950,
    faultHistory: {
      "Seal failure": { jobs: 80, successRate: 97 },
      "Water logging": { jobs: 55, successRate: 92 },
      "Overheating": { jobs: 120, successRate: 98 }
    },
    hasVehicle: true,
    phone: "9876543212",
    experience: 15,
    shopName: "Shiva Motor Works",
    shopNameKn: "ಶಿವ ಮೋಟರ್ ವರ್ಕ್ಸ್",
    location: "Kushtagi",
    locationKn: "ಕುಷ್ಟಗಿ",
    serviceRadius: 30,
    serviceAreas: ["Kushtagi","Hanumasagar","Mudenur","Tavaragera","Hiremannapur","Lingadahalli","Kadekoppa"],
    skills: ["Monoblock Pump", "Agricultural Motors"],
    skillsKn: ["ಮೋನೋಬ್ಲಾಕ್ ಪಂಪ್", "ಕೃಷಿ ಮೋಟರ್"],
    availability: "Busy",
    availabilityKn: "ಬ್ಯುಸಿ",
    rating: 4.7,
    completedJobs: 421
  },

  {
    id: "M004",
    name: "Mahantesh P",
    nameKn: "ಮಹಾಂತೇಶ್ ಪಿ",
    lat: 15.6171,
    lng: 76.0142,
    faultHistory: {
      "Winding burnout": { jobs: 65, successRate: 95 },
      "Suction pipe blockage": { jobs: 40, successRate: 100 },
      "Cable fault": { jobs: 30, successRate: 99 }
    },
    hasVehicle: true,
    phone: "9876543213",
    experience: 10,
    shopName: "Mahantesh Electricals",
    shopNameKn: "ಮಹಾಂತೇಶ್ ಎಲೆಕ್ಟ್ರಿಕಲ್ಸ್",
    location: "Yelburga",
    locationKn: "ಯಲಬುರ್ಗ",
    serviceRadius: 30,
    serviceAreas: ["Yelburga","Kuknoor","Talakal","Bannikoppa","Hirevankalakunta","Chikkabannigol","Mangalur"],
    skills: ["Submersible Pump", "Borewell Motors"],
    skillsKn: ["ಸಬ್‌ಮರ್ಸಿಬಲ್ ಪಂಪ್", "ಬೋರ್‌ವೆಲ್ ಮೋಟರ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.6,
    completedJobs: 226
  },

  {
    id: "M005",
    name: "Ramesh H",
    nameKn: "ರಮೇಶ್ ಹೆಚ್",
    lat: 15.5683,
    lng: 76.4253,
    faultHistory: {
      "Bearing seizure": { jobs: 110, successRate: 98 },
      "Impeller damage": { jobs: 85, successRate: 96 },
      "Overheating": { jobs: 150, successRate: 99 }
    },
    hasVehicle: true,
    phone: "9876543214",
    experience: 18,
    shopName: "Ramesh Rewinding Centre",
    shopNameKn: "ರಮೇಶ್ ರಿವೈಂಡಿಂಗ್ ಸೆಂಟರ್",
    location: "Kanakagiri",
    locationKn: "ಕನಕಗಿರಿ",
    serviceRadius: 30,
    serviceAreas: ["Kanakagiri","Gangavathi","Karatagi","Navali","Budagumpa","Muslapur","Hasgal","Hatti"],
    skills: ["Openwell Pump", "Industrial Motors"],
    skillsKn: ["ಓಪನ್ ವೆಲ್ ಪಂಪ್", "ಇಂಡಸ್ಟ್ರಿಯಲ್ ಮೋಟರ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.9,
    completedJobs: 503
  },

  {
    id: "M006",
    name: "Prakash S",
    nameKn: "ಪ್ರಕಾಶ್ ಎಸ್",
    lat: 15.5786,
    lng: 76.6341,
    faultHistory: {
      "Starter panel fault": { jobs: 45, successRate: 94 },
      "Capacitor failure": { jobs: 60, successRate: 98 },
      "Cable fault": { jobs: 20, successRate: 100 }
    },
    hasVehicle: false,
    phone: "9876543215",
    experience: 7,
    shopName: "Prakash Motor Clinic",
    shopNameKn: "ಪ್ರಕಾಶ್ ಮೋಟರ್ ಕ್ಲಿನಿಕ್",
    location: "Karatagi",
    locationKn: "ಕರತಗಿ",
    serviceRadius: 30,
    serviceAreas: ["Karatagi","Gangavathi","Anegundi","Marlanahalli","Basapura","Mustur","Challur"],
    skills: ["Monoblock Pump"],
    skillsKn: ["ಮೋನೋಬ್ಲಾಕ್ ಪಂಪ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.5,
    completedJobs: 167
  },

  {
    id: "M007",
    name: "Mallikarjun T",
    nameKn: "ಮಲ್ಲಿಕಾರ್ಜುನ ಟಿ",
    lat: 15.3267,
    lng: 76.3312,
    faultHistory: {
      "Winding burnout": { jobs: 55, successRate: 93 },
      "Seal failure": { jobs: 80, successRate: 96 },
      "Water logging": { jobs: 45, successRate: 90 }
    },
    hasVehicle: true,
    phone: "9876543216",
    experience: 11,
    shopName: "Mallikarjun Pump Care",
    shopNameKn: "ಮಲ್ಲಿಕಾರ್ಜುನ ಪಂಪ್ ಕೇರ್",
    location: "Munirabad",
    locationKn: "ಮುನಿರಾಬಾದ್",
    serviceRadius: 30,
    serviceAreas: ["Munirabad","Koppal","Hosahalli","Hitnal","Bhagyanagar","Irkalgada","Halageri"],
    skills: ["Submersible Pump", "Openwell Pump"],
    skillsKn: ["ಸಬ್‌ಮರ್ಸಿಬಲ್ ಪಂಪ್", "ಓಪನ್ ವೆಲ್ ಪಂಪ್"],
    availability: "Busy",
    availabilityKn: "ಬ್ಯುಸಿ",
    rating: 4.8,
    completedJobs: 288
  },

  {
    id: "M008",
    name: "Siddappa R",
    nameKn: "ಸಿದ್ದಪ್ಪ ಆರ್",
    lat: 15.5292,
    lng: 76.0270,
    faultHistory: {
      "Shaft breakage": { jobs: 35, successRate: 88 },
      "Impeller damage": { jobs: 60, successRate: 95 }
    },
    hasVehicle: true,
    phone: "9876543217",
    experience: 9,
    shopName: "Siddappa Motor Service",
    shopNameKn: "ಸಿದ್ದಪ್ಪ ಮೋಟರ್ ಸರ್ವೀಸ್",
    location: "Kuknoor",
    locationKn: "ಕೂಕನೂರು",
    serviceRadius: 30,
    serviceAreas: ["Kuknoor","Yelburga","Talakal","Mudenur","Hiremannapur","Chikkabannigol"],
    skills: ["Borewell Pump", "Agricultural Motors"],
    skillsKn: ["ಬೋರ್‌ವೆಲ್ ಪಂಪ್", "ಕೃಷಿ ಮೋಟರ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.7,
    completedJobs: 214
  },

  {
    id: "M009",
    name: "Veeresh B",
    nameKn: "ವೀರೇಶ್ ಬಿ",
    lat: 15.7538,
    lng: 76.3533,
    faultHistory: {
      "Winding burnout": { jobs: 120, successRate: 97 },
      "Bearing seizure": { jobs: 95, successRate: 99 },
      "Voltage fluctuation damage": { jobs: 65, successRate: 96 }
    },
    hasVehicle: true,
    phone: "9876543218",
    experience: 14,
    shopName: "Veeresh Electrical Works",
    shopNameKn: "ವೀರೇಶ್ ಎಲೆಕ್ಟ್ರಿಕಲ್ ವರ್ಕ್ಸ್",
    location: "Tavaragera",
    locationKn: "ತಾವರಗೇರ",
    serviceRadius: 30,
    serviceAreas: ["Tavaragera","Kushtagi","Hanumasagar","Kadekoppa","Lingadahalli","Mudenur"],
    skills: ["Submersible Pump", "Monoblock Pump"],
    skillsKn: ["ಸಬ್‌ಮರ್ಸಿಬಲ್ ಪಂಪ್", "ಮೋನೋಬ್ಲಾಕ್ ಪಂಪ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.9,
    completedJobs: 389
  },

  {
    id: "M010",
    name: "Nagaraj G",
    nameKn: "ನಾಗರಾಜ್ ಜಿ",
    lat: 15.3524,
    lng: 76.1428,
    faultHistory: {
      "Capacitor failure": { jobs: 40, successRate: 98 },
      "Suction pipe blockage": { jobs: 25, successRate: 92 }
    },
    hasVehicle: false,
    phone: "9876543219",
    experience: 6,
    shopName: "Nagaraj Pump Solutions",
    shopNameKn: "ನಾಗರಾಜ್ ಪಂಪ್ ಸೊಲ್ಯೂಷನ್ಸ್",
    location: "Bhagyanagar",
    locationKn: "ಭಾಗ್ಯನಗರ",
    serviceRadius: 30,
    serviceAreas: ["Bhagyanagar","Koppal","Munirabad","Hosahalli","Hitnal","Kunikeri","Halageri"],
    skills: ["Openwell Pump", "Domestic Water Pumps"],
    skillsKn: ["ಓಪನ್ ವೆಲ್ ಪಂಪ್", "ಮನೆ ನೀರಿನ ಪಂಪ್"],
    availability: "Available",
    availabilityKn: "ಖಾಲಿ ಇದ್ದಾರೆ",
    rating: 4.4,
    completedJobs: 124
  }
];

module.exports = mechanics;